//Importing react-scroll
import { Link } from "react-scroll";
//Importing react
import { useEffect } from "react";

//Importing CSS
import './Home.css'
//importing images
import easyNpsLogo from '../../images/easyNpsLogo.png';
import qrCodeScan from '../../images/qrCodeScan.png';
//fetch URL paramaters
const params = new URLSearchParams(window.location.search);

function Home(){

    //Changing theme color dynamically. Blue was by default in index.html
    document.head.querySelector('meta[name="theme-color"]').content = "#ffffff"

    //Checking if the URL is valid
    const urlValid = ()=>{
        if(params.get('l') && params.get('pt') && params.get('a') && params.get('b') && params.get('c')){
          return true
        }else{
          return false
        }
      }
  
      //checking if URL is valid
      useEffect(()=>{
       
        if(urlValid())
        { 
          window.location = `/bestbuy?l=${params.get('l')}&a=${params.get('a')}&b=${params.get('b')}&c=${params.get('c')}&pt=${params.get('pt')}`
        }
        },[])
  
        
return(
    <>

    <div className="banner-home">
        <img src={easyNpsLogo} alt="Easy NPS Logo" className="logo"/>
    </div>

    <div className="main center-body">
        <h1 style={{fontSize:"5rem"}}>NPS</h1>
        <h3>is now made simple.</h3>
    </div>

    <div className="button center-body">
        <Link to="second" smooth={true}>
        <button className="learnMore">How does it work ?</button>
        </Link>
    </div>
    
    <div className="image-container">
        <img alt="" src={qrCodeScan}/>
    </div>

    <div className="second" id="second">
        <h3>What is Easy NPS ?</h3>
        <div className="center-body">
            <p>Easy NPS is tool that makes filling online surveys easier for customers. You just need to scan the QR code generated by the associate, fill the survey and submit.</p>
        </div>
    </div>
    </>
)
}

export default Home;